<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Contains rrg_test.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rrg_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rrg_test module.
    case 'help.page.rrg_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is my custom module for altering existing drupal site information') . '</p>';
      return $output;

    default: 
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rrg_test_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  $site_config = \Drupal::config('system.site');
  $siteapikey = $site_config->get('siteapikey');
    
  $form['site_information']['siteapikey'] = [
    '#type' => 'textfield',
    '#title' => t('Site API Key'),
    '#maxlength' => 60,
    '#size' => 60,
    '#default_value' => ($siteapikey)?$siteapikey:'No API Key yet',
    '#weight' => 10,
  ];
  
  $form['actions']['submit']['#value'] = t('Update Configuration');
  // Custom submit callback
  $form['actions']['submit']['#submit'][] = 'rrg_form_submit';
}

/**
 * Implement custom callback submit function 
 */
function rrg_form_submit(array $form, FormStateInterface $form_state){
  $config = \Drupal::service('config.factory')->getEditable('system.site');
  $config->set('siteapikey', $form_state->getValue('siteapikey'))
    ->set('name', $form_state->getValue('site_name'))
    ->set('mail', $form_state->getValue('site_mail'))
    ->set('slogan', $form_state->getValue('site_slogan'))
    ->set('page.front', $form_state->getValue('site_frontpage'))
    ->set('page.403', $form_state->getValue('site_403'))
    ->set('page.404', $form_state->getValue('site_404'))
    ->save();
  if($form_state->getValue('siteapikey') != "No API Key yet"){
    drupal_set_message(t('Site API Key has been saved with ' . $form_state->getValue('siteapikey'). ' '), 'status');    
  }  
}
